### PR TITLE
Add rule for TypeScript

### PR DESCRIPTION
**Pull request by stephenlacy**
- add rule for TypeScript, follows CoffeeScript rule style.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by stephenlacy** [comment]
:smile:

**Comment by stephenlacy** [comment]
Are you open to accept other rules for compile-to-js languages?
Obviously not all 100+ pre-languages, just the popular ones.

**Comment by sindresorhus** [comment]
Sure, but not yet. I want to rework how the rules work first. Open an issue ;)

**Pull request merged**
